### ISSUE TITLE
With new NVIDIA Graphics driver 560.94, CUDA-Q programs fail to run

### ISSUE THREAD

**Issue by rtvuser1** [NVIDIA/cuda-quantum#2295]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

I just discovered that none of my CUDAQ containers are able to execute on my gpu system any more.  
I hadn't run the code for a few days, and now I am getting the error below anytime I run either a python or a cpp CUDA quantum program. 
Here I am running in the 0.8 container, the example that comes with CUDA quantum 0.8 under examples/python:

    python bernstein_vazirani.py
    Traceback (most recent call last):
      File "/home/cudaq/apps/examples080/python/bernstein_vazirani.py", line 1, in <module>
        import cudaq
      File "/opt/nvidia/cudaq/cudaq/__init__.py", line 43, in <module>
        from .kernel.kernel_decorator import kernel, PyKernelDecorator
      File "/opt/nvidia/cudaq/cudaq/kernel/kernel_decorator.py", line 15, in <module>
        from ..mlir.dialects import quake, cc, func
      File "/opt/nvidia/cudaq/cudaq/mlir/dialects/quake.py", line 10, in <module>
        from .._mlir_libs._quakeDialects.quake import *
    ImportError: [custatevec] %named symbol not found in check_gpu_compatibility (line 36)

This all worked fine a couple days ago, when I did a few video conversions using ffmpeg (which might have used the gpu).
Looking into this more, it appears the ffmpeg tool installed a new NVIDIA Graphics driver a couple days ago, which seems to be the source of the problem.  The one installed now is: 560.94, which appears to be the latest, and apparently CUDAQ doesn't work with this. 
I pulled the cudaq "latest" image and that doesn't work either.

This leaves me somewhat "dead in the water". 

Perhaps if I knew what version of the NVIDIA driver was tested with 0.8 release?

### Steps to reproduce the bug

This issue will probably appear for anyone with the new driver 560.94

### Expected behavior

It should work of course

### Is this a regression? If it is, put the last known working version (or commit) here.

Previously I had NVIDIA - Display - 31.0.15.2824 installed.

### Environment

- **CUDA Quantum version**:  0.8.0 and "latest"
- **Python version**: 3.12
- **C++ compiler**: 
- **Operating system**: Docker container running on Windows platform

**Comment by bmhowe23** [comment]
> Perhaps if I knew what version of the NVIDIA driver was tested with 0.8 release?

Hi @rtvuser1, I don't have the version that 0.8.0 was tested with available off hand, but I believe our nightly GitHub CI tests are running on driver version 550.

With that being said, if you're willing, it might be worth trying our 0.8.0 wheels in a fresh Docker container. Assuming you're running on x86, this is the simplest way to install them and fire up a quick test.

```bash
docker pull ubuntu:22.04
docker run -it --gpus all --rm --name test-container ubuntu:22.04
# Then inside container
cd
nvidia-smi
# Verify that the above command produced something reasonable without error messages. If no errors, then proceed.
# If an error occurred above, then the problem is more fundamental than CUDA-Q itself.
apt update && apt install -y python3 python3-pip
pip install cuda-quantum
CUDAQ_LOG_LEVEL=info python3 -c 'import cudaq'
# Look for this message: "[runtime] Setting the circuit simulator to cusvsim-fp32"
```

Once you're done with that container, you can simply type `exit`, and it will exit the container and remove it (since it was launched with the `--rm` option).

I'm curious to know if any problems occur in the `nvidia-smi` command, or if it makes it past that point.

**Comment by rtvuser1** [comment]
New info:

Problem unrelated to the docker container.

By reverting to version 551.86 of the NVIDIA Graphics Driver and disabling Windows update, everything works fine now in my version 0.8 of CUDA-Q.  However, the next Windows update will likely generate the issue again.

I have not tested other driver versions.  But the evidence here suggests that somewhere between version 551.68 in Mar 24 and 560.94 Aug 20, the problem started to appear, but I do not know when.  I believe I also tested the latest version, 565.90 but that did not work.
(however, I did not try a system reboot after that so I do not know for sure. It would be helpful if you could test CUDA Q on the latest 565.90 version and let me know before I try again).

For now I will use the 551.68 driver to continue the work underway ...

**Comment by rtvuser1** [comment]
> > Perhaps if I knew what version of the NVIDIA driver was tested with 0.8 release?
> 
> Hi [@rtvuser1](https://github.com/rtvuser1), I don't have the version that 0.8.0 was tested with available off hand, but I believe our nightly GitHub CI tests are running on driver version 550.
> 
> With that being said, if you're willing, it might be worth trying our 0.8.0 wheels in a fresh Docker container. Assuming you're running on x86, this is the simplest way to install them and fire up a quick test.
> 
> docker pull ubuntu:22.04
> docker run -it --gpus all --rm --name test-container ubuntu:22.04
> # Then inside container
> cd
> nvidia-smi
> # Verify that the above command produced something reasonable without error messages. If no errors, then proceed.
> # If an error occurred above, then the problem is more fundamental than CUDA-Q itself.
> apt update && apt install -y python3 python3-pip
> pip install cuda-quantum
> CUDAQ_LOG_LEVEL=info python3 -c 'import cudaq'
> # Look for this message: "[runtime] Setting the circuit simulator to cusvsim-fp32"
> Once you're done with that container, you can simply type `exit`, and it will exit the container and remove it (since it was launched with the `--rm` option).
> 
> I'm curious to know if any problems occur in the `nvidia-smi` command, or if it makes it past that point.

Is the 0.8.0 wheel that same as the "latest" Docker image?  If so, I can more easily try that since I do not have cudaq installed locally

**Comment by bmhowe23** [comment]
> Is the 0.8.0 wheel that same as the "latest" Docker image? If so, I can more easily try that since I do not have cudaq installed locally

No, but the above test is primarily meant as a test to help isolate the problem. It will pull the wheel from pypi into the test container during the test, so you should only need Docker locally installed to start the test.

**Comment by rtvuser1** [comment]
To whom it may concern:

It appears this problem with the nvidia driver is still a problem.

I had another windows update perform an upgrade from my 551.83 version of the RTX 4070 driver.
It bumped it to 565.90 this time, and then I got the same error as before.
I tried version 572.83, the latest, and I tried using 560.81, the earlies that remains available ... and they both also failed.

The earlier 551.86 that worked before is not available on the download site any more.
Fortunately, I saved the earlier 551.86 exe file and reinstalled in, rebooted and now everything works.

The question is: how do other people operate?  I am running on Windows, and I believe it is using WSL 2.
Sometimes on a system update, it upgrades the driver, but the driver causes a failure with CUDA-Q , versions 0.8.0, CU12-0.9.1, CU12-0.10.0

Has anyone looked into this issue yet?

**Comment by bmhowe23** [comment]
Hi @rtvuser1 - assuming your WSL2 Linux distro is Ubuntu, after updating the driver, you may need to run `sudo apt update && sudo apt install --only-upgrade nvidia-container-toolkit` from your WSL2 shell. Be sure to run this command without any containers running.

I saw a similar error message to the one you pasted in the original issue while using `nvidia-container-toolkit 1.14.3-1` with driver 572.61, but the problem went away after updating the toolkit to `1.17.5-1` (latest as of today), so hopefully this works for you, too.

**Comment by rtvuser1** [comment]
Hi @bmhowe23 I managed to make things work a couple of weeks ago by reverting to the older 551.86 driver that I had stashed away (even tho it is no longer available on your site).  Since this got the system running and there were deadlines pendng, I did not attempt to put it back to the latest driver and test again.
I will try out your suggested approach sometime in the days coming up.

**Comment by bmhowe23** [comment]
Hi @rtvuser1 - sorry for the slow response; I'm just seeing the questions in the second half of this message right now because I don't think GitHub emails me when edits are made to the original message.

> Shouldn't this be something that is just handled for the user, perhaps in the docker container

I will reach out to the `nvidia-container-toolkit` team and ask if there is a way to make them auto-recognize when the driver has been updated and suggest that the user update `nvidia-container-toolkit` at that time. But perhaps before I do that, can you please confirm that resolved the issue for you? Thanks!

**Comment by rtvuser1** [comment]
Actually, I have been neglect in trying the update of the
container-toolkit.  The hesitation is that I use the system on a daily
basis, and have not set aside time to deal with the downtime if I try this
and it breaks and then I have no solution.  It works now, and I didn't want
to break it.  However, I am setting up another system and when I do that I
will have some freedom to try the update of the container-toolkit.

**Comment by rtvuser1** [comment]
Actually, I have been neglect in trying the update of the container-toolkit.  The hesitation is that I use the system on a daily basis, and have not set aside time to deal with the downtime if I try this and it breaks and then I have no solution.  It works now, and I didn't want to break it.  However, I am setting up another system and when I do that I will have some freedom to try the update of the container-toolkit.

**Comment by khalatepradnya** [comment]
Hi @rtvuser1 ,
Thank you for the detailed reporting across multiple driver versions. Based on investigation in this thread, this appears to be caused by a version mismatch between the NVIDIA graphics driver and nvidia-container-toolkit on WSL2, rather than a CUDA-Q issue. The suggested fix is: ```sudo apt update && sudo apt install --only-upgrade nvidia-container-toolkit```
(run from your WSL2 shell with no containers active).

If you're able to confirm the toolkit update resolves things on your end, that would be very helpful. 
Keeping open for confirmation.

@bmhowe23 - if you happen to have a public / shareable tracker of the issue with `nvidia-container-toolkit` team, can you add here.

**Comment by aminx-hue** [comment]
Since this issue is rather old and there seems to be a solution, I am going to close for now. If this doesn't work for you please open the issue again.
